language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - sudo apt-get -qq update
  - sudo apt-get -y install yasm nasm libmp3lame-dev
  - cd $TRAVIS_BUILD_DIR
  - pip install -r requirements.txt
  - mkdir ~/bin/
  - python test/ffmpeg_bin.py 05861434675432854607
  - chmod 755 ~/bin/ffmpeg
script: python -m pytest test
